import { test, expect } from '@playwright/test';

test('develop, inspect, edit, assess, and learn from binary feedback',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#access=standout-e2e-observer');
  await expect(page.getByRole('heading',{name:'Turn your evidence into a compelling submission.'})).toBeVisible();
  await page.getByLabel('Direction for this round').fill('Write a concise proposal with a specific research question and grounded evidence.');
  await page.getByRole('button',{name:'Develop submission',exact:true}).click();
  await expect(page.getByText('Round complete',{exact:true}).first()).toBeVisible({timeout:15000});
  await expect(page.locator('.artifact-body')).toContainText('A reproducible research contribution');
  await expect(page.getByText('Your private assessment',{exact:true})).toBeVisible();
  await expect(page.getByText('0 previous binary observations',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/studio-desktop.png',fullPage:true});
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download draft'}).click();
  expect((await download).suggestedFilename()).toMatch(/\.md$/);
  await page.getByRole('button',{name:'Edit draft',exact:true}).click();
  const text=page.getByLabel('Submission text');const old=await text.inputValue();
  await text.fill(old+'\n\nThe scope will be reviewed with the team before implementation.');
  await page.getByRole('button',{name:'Save new version',exact:true}).click();
  await expect(page.getByText('This version has not been assessed yet.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Evaluate this version',exact:true}).click();
  await expect(page.getByText('Your private assessment',{exact:true})).toBeVisible({timeout:15000});
  await page.getByRole('button',{name:'Explore next round',exact:true}).click();
  await expect(page.getByRole('option',{name:/Refined approach 1/})).toHaveCount(1,{timeout:15000});
  await expect(page.getByRole('button',{name:'Explore next round',exact:true})).toBeEnabled({timeout:15000});
  await page.getByLabel('Choose saved draft').selectOption({label:await page.getByRole('option',{name:/Refined approach 1/}).innerText()});
  await expect(page.getByText('36 previous binary observations',{exact:true})).toBeVisible();
  await expect(page.locator('.binary-history')).toContainText('No scores or critiques were provided');
  await page.getByRole('button',{name:'See selection outcomes',exact:true}).click();
  await expect(page.getByText('Kimi assessment',{exact:true})).toBeVisible();
  await expect(page.locator('.trial-table tbody tr')).toHaveCount(24);
  await page.getByRole('button',{name:/Inspect world 1,/}).first().click();
  await expect(page.getByRole('dialog').locator('pre')).not.toContainText('PRIVATE_CRITIQUE_SENTINEL');
  await page.getByRole('tab',{name:'Observer view'}).click();
  await expect(page.getByText('Voice & specificity',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Submission studio',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('.artifact-body')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/studio-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
});
