import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('/#access=standout-e2e-observer');
  await expect(page.getByRole('heading', { name: 'Fieldnotes Research Fellowship' })).toBeVisible();
  await expect(page).toHaveURL('http://127.0.0.1:5174/');
  await page.getByRole('button', { name: 'Project brief', exact: true }).click();
});

test('inspect binary feedback, private diagnostics, replay, and export', async ({ page }) => {
  const browserErrors: string[] = [];
  page.on('pageerror', e => browserErrors.push(e.message));
  await page.screenshot({ path: 'test-results/brief-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Experiments', exact: false }).first().click();
  await page.getByLabel('Comparison', { exact: true }).selectOption((await page.locator('#comparison option').last().getAttribute('value'))!);
  await expect(page.getByRole('heading', { name: 'How each strategy performed' })).toBeVisible();
  await expect(page.locator('.trial-table tbody tr')).toHaveCount(36);
  await page.screenshot({ path: 'test-results/experiments-desktop.png', fullPage: true });
  await page.getByRole('button', { name: /Inspect world 1,/ }).first().click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('pre')).toContainText('"passed":');
  await expect(dialog.locator('pre')).not.toContainText('score');
  await expect(dialog.getByText('What contributed to the score')).toHaveCount(0);
  await dialog.getByRole('tab', { name: 'Observer view' }).click();
  await expect(dialog.getByText('What contributed to the score')).toBeVisible();
  await dialog.getByText('Focus coverage', { exact: true }).click();
  await expect(dialog.getByText(/This measures keyword coverage/)).toBeVisible();
  await page.screenshot({ path: 'test-results/inspector-desktop.png' });
  await dialog.getByRole('button', { name: 'Verify replay' }).click();
  await expect(page.getByRole('status')).toContainText('Replay matches');
  await dialog.getByRole('button', { name: 'Close dialog' }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export experiment data' }).click();
  await expect((await download).suggestedFilename()).toMatch(/^standout-project_.*\.json$/);
  expect(browserErrors).toEqual([]);
});

test('create project, add evidence, version strategies and drafts, and run a comparison', async ({ page }) => {
  const failedRequests: string[] = [];
  page.on('response', response => { if (response.status() >= 400) failedRequests.push(response.url()); });
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Project name').fill('Browser test research proposal');
  await dialog.getByLabel('Institution', { exact: true }).fill('Test institute');
  await dialog.getByLabel('Original posting').fill('We seek a researcher who can produce reproducible research on public health with transparent evaluation methods.');
  await dialog.getByLabel('Deadline (UTC)').fill('2030-12-31');
  await dialog.getByLabel('Focus terms').fill('public health, reproducible');
  await dialog.getByLabel('Reservation conditions').fill('No relocation and a maximum of 20 hours weekly.');
  await dialog.getByRole('button', { name: 'Create project' }).click();
  await expect(page.getByRole('heading', { name: 'Browser test research proposal' })).toBeVisible();
  await page.getByRole('button', { name: 'Evidence bank', exact: true }).click();
  await page.getByRole('button', { name: 'Add evidence', exact: true }).first().click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Title').fill('Open methods project');
  await dialog.getByLabel('Fact or observation').fill('I produced a reproducible public health analysis of 120 observations and published the methods, code, and limitations for independent review.');
  await dialog.getByLabel('Source or reference').fill('Test fixture: methods report');
  await dialog.getByRole('button', { name: 'Save evidence' }).click();
  await expect(page.getByRole('heading', { name: 'Open methods project' })).toBeVisible();
  await page.getByRole('button', { name: 'Strategies', exact: true }).click();
  await page.getByRole('button', { name: 'New strategy', exact: true }).first().click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Strategy name').fill('Focused delivery');
  await dialog.getByLabel('Change hypothesis').fill('Use the research evidence to support a narrow delivery plan.');
  await dialog.getByLabel('Opening emphasis').selectOption('delivery');
  await dialog.getByLabel('Timed milestones').fill('3');
  await dialog.getByRole('button', { name: 'Save strategy version' }).click();
  await expect(page.getByRole('heading', { name: 'Focused delivery', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Generate draft' }).click();
  dialog = page.getByRole('dialog');
  const original = await dialog.getByLabel('Submission text').inputValue();
  await dialog.getByLabel('Submission text').fill(`${original}\n\nMy first review would clarify the expected users of the analysis.`);
  await expect(dialog.getByRole('button', { name: 'Evaluate saved version' })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Save new version' }).click();
  await expect(dialog.getByText(/Human-edited version/)).toBeVisible();
  await dialog.getByRole('button', { name: 'Evaluate saved version' }).click();
  await expect(page.getByRole('heading', { name: 'How each strategy performed' })).toBeVisible();
  await expect(page.locator('.trial-table tbody tr')).toHaveCount(12);
  await page.getByRole('button', { name: 'Strategies', exact: true }).click();
  await page.getByRole('button', { name: 'Branch or merge', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Strategy name').fill('Delivery with alternatives');
  await dialog.getByLabel('Include a hypothesis and alternative comparison').check();
  await dialog.getByRole('button', { name: 'Save strategy version' }).click();
  await expect(page.getByRole('heading', { name: 'Delivery with alternatives', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Branch or merge', exact: true }).last().click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Strategy name').fill('Merged delivery strategy');
  await dialog.getByLabel('Optional second parent').selectOption({ label: 'Focused delivery · v1' });
  await dialog.getByRole('button', { name: 'Save strategy version' }).click();
  await expect(page.getByRole('heading', { name: 'Merged delivery strategy', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/lineage-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Reference comparison', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Hidden worlds').fill('4');
  await dialog.getByRole('button', { name: 'Run comparison' }).click();
  await expect(page.locator('.comparison-table tbody tr')).toHaveCount(3);
  await expect(page.locator('.trial-table tbody tr')).toHaveCount(12);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Browser test research proposal' })).toBeVisible();
  await page.getByRole('button', { name: 'Strategies', exact: true }).click();
  await expect(page.locator('.policy-item')).toHaveCount(3);
  await expect(page.getByRole('alert')).toHaveCount(0);
  expect(failedRequests).toEqual([]);
});

test('mobile workspace stays within viewport and dialogs remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/brief-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Experiments', exact: false }).first().click();
  await page.getByLabel('Comparison', { exact: true }).selectOption((await page.locator('#comparison option').last().getAttribute('value'))!);
  await expect(page.locator('.trial-table tbody tr')).toHaveCount(36);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: /Inspect world 1,/ }).first().click();
  await page.getByRole('tab', { name: 'Observer view' }).click();
  await expect(page.getByRole('tab', { name: 'Observer view' })).toHaveAttribute('aria-selected', 'true');
  await page.screenshot({ path: 'test-results/inspector-mobile.png' });
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.getByRole('button', { name: 'Close dialog' }).click();
});
