import { useEffect, useState } from 'react';
import { ArrowDownToLine, Check, LockKeyhole, Play, Plus, ShieldCheck, ExternalLink } from 'lucide-react';
import { api, post } from './api';
import type { Project } from './types';
import './research.css';

const methods: Record<string,string> = {fixed:'Fixed drafting',random:'Random exploration',adaptive:'Binary adaptation',full:'Full feedback',shuffled:'Shuffled feedback'};
type Stage = 'train'|'validation'|'test';
type Study = {id:string;name:string;demo:boolean;status:{state:string}};
type Result = {method:string;rate:number|null;interval:number[]|null;delta:number|null;delta_interval:number[]|null;opportunities:number};
type Policy = {id:string;name:string;method:string;instructions:string;hash:string;feedback_received:{passed:boolean}[];diagnostics_received:unknown[]};
type Detail = {experiment:{id:string;name:string;demo:boolean;rounds:number;replicates:number;protocol_hash:string;artifact_type:string;opportunities:{id:string;name:string;split:string;family:string}[];budget:{per_method_call_ceiling:Record<Stage,number>;shared_selector_calls:Record<Stage,number>;total_call_ceiling:number;basis:string}};
  status:{state:string;stage?:Stage;message:string};progress:{message:string}[];sample_count:number;review_count:number;policies:Policy[];freeze:{hash:string;policies:Record<string,Policy>}[];
  usage:{method:string;calls:number;tokens:number;elapsed_ms:number}[];
  summary:{methods:Result[];human:{method:string;score:number|null;reviewed:number}[];clusters:number;complete_opportunities:number;planned_opportunities:number;interval_note:string;unit:string}};
const pct = (n:number|null) => n === null ? 'Awaiting test' : `${(n*100).toFixed(1)}%`;
function download(value:unknown,name:string) {const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}

export default function Research({projects}:{projects:Project[]}) {
  const [studies,setStudies]=useState<Study[]>([]),[id,setId]=useState(''),[data,setData]=useState<Detail|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[create,setCreate]=useState(false),[reviewLink,setReviewLink]=useState('');
  const [splits,setSplits]=useState<Record<string,string>>({}),[families,setFamilies]=useState<Record<string,string>>({});
  const [name,setName]=useState('Held-out submission study'),[rounds,setRounds]=useState(2),[reps,setReps]=useState(2);
  async function loadList(){const list=await api<Study[]>('/research');setStudies(list);return list;}
  useEffect(()=>{loadList().then(list=>setId(list.at(-1)?.id||'')).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!id)return;let alive=true;setData(null);setReviewLink('');
    const load=()=>api<Detail>(`/research/${id}`).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});
    void load();const t=setInterval(load,2500);return()=>{alive=false;clearInterval(t);};},[id]);
  async function action(task:()=>Promise<void>){setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function register(demo:boolean){await action(async()=>{
    const body=demo?{request_key:crypto.randomUUID()}:{name,rounds,replicates:reps,seed:17,artifact_type:'Proposal',request_key:crypto.randomUUID(),assignments:projects.filter(p=>splits[p.id]).map(p=>({project_id:p.id,split:splits[p.id],family:families[p.id]||p.institution}))};
    const exp=await post<{id:string}>(demo?'/research/demo':'/research',body);await loadList();setId(exp.id);setCreate(false);
  });}
  const state=data?.status.state;
  const next:Stage|null=state==='created'?'train':state==='trained'?'validation':state==='frozen'?'test':null;
  const stageNames={train:'Run training',validation:'Validate and freeze policies',test:'Run held-out test'};
  const completed=state==='completed';
  return <div className="research-page">
    <header className="research-head"><div><h1>Does the strategy actually learn?</h1><p>Compare five methods on opportunities the optimizer has never seen.</p></div><a className="button secondary" href="/showcase">Product tour<ExternalLink size={15}/></a></header>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="research-toolbar"><label>Research study<select value={id} onChange={e=>setId(e.target.value)}><option value="" disabled>Choose a study</option>{studies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="button secondary" onClick={()=>setCreate(!create)}><Plus size={15}/>Register study</button><button className="button secondary" disabled={busy} onClick={()=>register(true)}>Create fictional pilot</button></div>
    {create&&<form className="research-setup" onSubmit={e=>{e.preventDefault();void register(false);}}><h2>Freeze the protocol before running</h2><p>Group related postings under one family. Institutions and duplicate postings cannot cross splits. Evidence and postings are snapshotted now.</p><label>Study name<input value={name} onChange={e=>setName(e.target.value)} required minLength={3}/></label>
      <div className="research-fields"><label>Training rounds<input type="number" value={rounds} min={2} max={5} onChange={e=>setRounds(+e.target.value)}/></label><label>Drafts per policy per opportunity<input type="number" value={reps} min={2} max={5} onChange={e=>setReps(+e.target.value)}/></label></div>
      {projects.map(p=><div className="assignment" key={p.id}><span>{p.name}</span><label>Family<input aria-label={`Family for ${p.name}`} value={families[p.id]??p.institution} onChange={e=>setFamilies({...families,[p.id]:e.target.value})}/></label><label>Partition<select aria-label={`Partition for ${p.name}`} value={splits[p.id]||''} onChange={e=>setSplits({...splits,[p.id]:e.target.value})}><option value="">Exclude</option><option value="train">Training</option><option value="validation">Validation</option><option value="test">Test</option></select></label></div>)}
      <button className="button primary" disabled={busy}>Register immutable protocol</button></form>}
    {!data&&!id&&<div className="research-empty"><ShieldCheck size={36}/><h2>A fair comparison starts before the first draft.</h2><p>Register your opportunities, or create a six-opportunity fictional pilot to explore the workflow. Registration makes no model calls.</p><div className="empty-partitions"><span>Train<br/><small>Improve policies</small></span><span>Validate<br/><small>Select and freeze</small></span><span>Test<br/><small>Measure transfer</small></span></div></div>}
    {data&&<>
      {data.experiment.demo&&<p className="research-caution">Fictional pilot · synthetic dossiers and institutions. Running stages uses the configured model. No result is precomputed.</p>}
      <div className="partition-rail" aria-label="Experimental partitions">{(['train','validation','test'] as Stage[]).map((s,i)=>{
        const done=s==='train'?['trained','frozen','completed'].includes(state||''):s==='validation'?['frozen','completed'].includes(state||''):completed;
        return <section key={s} className={done?'partition done':next===s||data.status.stage===s&&state==='running'?'partition active':'partition'}><div><span>{i+1}. {s==='train'?'Training':s==='validation'?'Validation & freeze':'Held-out test'}</span>{done?<Check size={18}/>:s==='test'?<LockKeyhole size={18}/>:null}</div><strong>{data.experiment.opportunities.filter(o=>o.split===s).length} {data.experiment.opportunities.filter(o=>o.split===s).length===1?'opportunity':'opportunities'}</strong><small>{s==='train'?'Feedback may change instructions':s==='validation'?'Choose from saved candidates':'Frozen instructions; no optimization'}</small><details><summary>View assignments</summary>{data.experiment.opportunities.filter(o=>o.split===s).map(o=><p key={o.id}>{o.name}<small>Family: {o.family}</small></p>)}</details></section>;
      })}</div>
      <section className="stage-control" aria-live="polite"><div><h2>{state==='running'?'Experiment running':state==='frozen'?'Policies sealed. Ready for the test.':state==='completed'?'Test complete. Add an independent review.':state==='failed'?'Experiment stopped':state==='trained'?'Training complete':'Protocol registered'}</h2><p>{state==='running'?data.progress[0]?.message||data.status.message:data.status.message}</p>{next&&<p className="small">This stage allows up to <strong>{data.experiment.budget.per_method_call_ceiling[next]*5+data.experiment.budget.shared_selector_calls[next]} model calls</strong>. Calls use your provider account. No automatic retry.</p>}</div>{next&&<button className="button primary" disabled={busy} onClick={()=>action(async()=>{await post(`/research/${id}/stages`,{stage:next,request_key:crypto.randomUUID()});setData(await api<Detail>(`/research/${id}`));})}><Play size={15}/>{stageNames[next]}</button>}{state==='running'&&<span className="spinner"/>}</section>
      {state==='failed'&&<p className="research-caution">Partial records are retained and excluded from complete comparisons. Inspect the export, correct the cause, then register a new study. Repeated paid stages are blocked.</p>}
      <div className="research-columns"><section><div className="section-title"><h2>Transfer to unseen opportunities</h2><span className="badge">{data.summary.complete_opportunities} / {data.summary.planned_opportunities} complete</span></div><p className="muted small">Mean simulated pass rate · paired against fixed drafting</p>
        <div className="method-plot">{data.summary.methods.map(m=><div className="method-line" key={m.method}><div><strong>{methods[m.method]}</strong><span>{pct(m.rate)}</span></div><div className="interval-track" aria-label={`${methods[m.method]}: ${pct(m.rate)}${m.interval?`, interval ${pct(m.interval[0])} to ${pct(m.interval[1])}`:''}`}>
          {m.interval&&<span className="interval-range" style={{left:`${m.interval[0]*100}%`,width:`${(m.interval[1]-m.interval[0])*100}%`}}/>}{m.rate!==null&&<span className="interval-point" style={{left:`${m.rate*100}%`}}/>}</div><small>{m.delta===null?'No held-out observations':`${m.delta>=0?'+':''}${(m.delta*100).toFixed(1)} percentage points vs fixed`}{m.delta_interval?` · paired 95% interval ${(m.delta_interval[0]*100).toFixed(1)} to ${(m.delta_interval[1]*100).toFixed(1)}`:''}</small></div>)}</div><div className="plot-scale"><span>0%</span><span>50%</span><span>100%</span></div><p className="research-note">{data.summary.interval_note}</p><p className="research-note">{data.summary.unit} Simulated passes are not real acceptance odds.</p></section>
        <section className="feedback-legend"><h2>What each optimizer can see</h2>{Object.entries(methods).map(([key,label])=><div key={key}><strong>{label}</strong><span>{key==='fixed'?'Predeclared instructions; no optimization':key==='random'?'Training dossiers; no history':key==='adaptive'?'Training pass/fail and prior policies':key==='full'?'Training scores and critiques (privileged)': 'Training binary labels randomly reassigned'}</span></div>)}<p className="research-note">All methods receive the same generation and judging slots. Shuffling preserves the pass fraction; it has no effect if every outcome is identical.</p></section></div>
      <section className="review-section"><div><h2>Independent human assessment</h2><p>Randomized documents with no method names, model scores, or policy histories. A separate reviewer link opens only the review queue.</p><p className="small">{data.review_count} {data.review_count===1?'review':'reviews'} recorded · human scores stay outside optimization</p></div><button className="button secondary" disabled={!completed||busy} onClick={()=>action(async()=>{const r=await post<{path:string}>(`/research/${id}/reviewer`,{});setReviewLink(r.path);})}>Create blind review link</button>
        {reviewLink&&<a className="button secondary" href={reviewLink} target="_blank" rel="noreferrer">Open reviewer workspace<ExternalLink size={15}/></a>}
        {data.review_count>0&&<div className="human-results">{data.summary.human.map(h=><div key={h.method}><strong>{methods[h.method]}</strong><span>{h.score===null?'Not reviewed':`${h.score.toFixed(2)} / 5`} · {h.reviewed} documents</span></div>)}<p className="research-note">Descriptive scores from one reviewer, averaged within opportunities. Partial coverage can bias comparisons; complete the queue first.</p></div>}
      </section>
      <details className="research-audit" open><summary>Budget and reproducibility</summary><p>{data.experiment.budget.basis}</p><div className="budget-table"><table><thead><tr><th>Method</th><th>Calls</th><th>Tokens</th><th>Model time</th></tr></thead><tbody>{data.usage.map(u=><tr key={u.method}><td>{methods[u.method]||'Shared selector setup'}</td><td>{u.calls}</td><td>{u.tokens.toLocaleString()}</td><td>{(u.elapsed_ms/1000).toFixed(1)} s</td></tr>)}</tbody></table></div><p className="research-note">Daily provider limits also apply. Registered ceiling: {data.experiment.budget.total_call_ceiling} calls across all stages. Dollar cost is provider-billed and not estimated here.</p><p className="hash-label">Protocol <code>{data.experiment.protocol_hash.slice(0,16)}</code>{data.freeze[0]&&<> · Freeze <code>{data.freeze[0].hash.slice(0,16)}</code></>}</p><button className="button secondary" onClick={()=>action(async()=>download(await api(`/research/${id}/export`),`research-${id}.json`))}><ArrowDownToLine size={15}/>Export complete research trace</button></details>
      {data.freeze[0]&&<section className="frozen-policies"><h2>Frozen policies</h2>{Object.entries(data.freeze[0].policies).map(([m,p])=><details key={m}><summary><LockKeyhole size={15}/>{methods[m]}<code>{p.hash.slice(0,10)}</code></summary><p>{p.instructions}</p><small>{p.feedback_received.length} training observations supplied; {p.diagnostics_received.length} detailed assessments supplied.</small></details>)}</section>}
    </>}
  </div>;
}

type Packet={packet_id:string;label:string;body:string;context:{posting:string;institution:string};evidence:{title:string;body:string}[];reviewed:boolean};
export function Reviewer(){
  const [token]=useState(()=>{const t=new URLSearchParams(location.hash.slice(1)).get('access')||sessionStorage.getItem('standout.reviewer')||'';if(t)sessionStorage.setItem('standout.reviewer',t);history.replaceState(null,'','/review');return t;});
  const [packets,setPackets]=useState<Packet[]>([]),[instructions,setInstructions]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const headers={Authorization:`Bearer ${token}`};
  async function load(){const r=await api<{packets:Packet[];instructions:string}>('/review',{headers});setPackets(r.packets);setInstructions(r.instructions);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const packet=packets.find(p=>!p.reviewed);
  return <main className="reviewer-page"><header><ShieldCheck size={24}/><h1>Independent document review</h1><p>{instructions}</p></header>{error&&<p role="alert" className="form-error">{error}</p>}
    {packet?<><div className="section-title"><h2>{packet.label}</h2><span>{packets.filter(p=>p.reviewed).length} / {packets.length} reviewed</span></div><details><summary>Posting and supporting evidence</summary><p>{packet.context.posting}</p>{packet.evidence.map((e,i)=><p key={i}><strong>{e.title}</strong><br/>{e.body}</p>)}</details><article className="review-document">{packet.body}</article><form key={packet.packet_id} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await postWithToken({packet_id:packet.packet_id,...Object.fromEntries(['clarity','specificity','credibility','feasibility'].map(k=>[k,Number(f.get(k))])),recommend:f.get('recommend')==='yes',notes:String(f.get('notes'))});await load();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
      <div className="review-ratings">{['Clarity','Specificity','Credibility','Feasibility'].map(k=><label key={k}>{k}<select aria-label={k} name={k.toLowerCase()} required defaultValue=""><option value="" disabled>Choose rating</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {['Weak','Limited','Adequate','Strong','Excellent'][v-1]}</option>)}</select></label>)}</div><label>Would you recommend this submission?<select aria-label="Would you recommend this submission?" name="recommend" required defaultValue=""><option value="" disabled>Choose</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>Evidence for your assessment<textarea name="notes" required minLength={10} maxLength={3000}/></label><button className="button primary" disabled={busy}>Save review and continue</button></form></>:packets.length?<p>All assigned documents reviewed. Your assessments are saved.</p>:!error?<p>Loading review assignment…</p>:null}</main>;
  async function postWithToken(body:unknown){return api('/review',{method:'POST',headers,body:JSON.stringify(body)});}
}
