import { useState } from 'react';
import { ArrowRight, Check, FileText, GitBranch, LockKeyhole, ShieldCheck, Code2, ExternalLink } from 'lucide-react';
import './research.css';

const walkthrough = [
  {title:'Start with facts.', label:'Evidence', body:'University research project: built a Python cleaning pipeline, compared two baselines, and documented error cases.', note:'Fictional applicant evidence. The writer can choose emphasis, not invent achievements.'},
  {title:'Make the approach explicit.', label:'Writing policy', body:'Lead with the institution’s problem. Use one concrete example of relevant work. Propose a bounded evaluation, with a baseline and a limitation.', note:'Instructions are saved as a policy version. Each revision preserves its parents and observed feedback.'},
  {title:'Turn the approach into a submission.', label:'Proposal excerpt', body:'I propose a twelve-week study of errors in public data. In a university project, I built a cleaning pipeline and compared two baselines. I would begin with a small, inspectable dataset, record failure cases, and test whether the proposed method improves on the baseline.', note:'Illustrative copy, not a generated experimental result. Historical claims and proposed work remain distinct.'},
  {title:'Learn without seeing the rubric.', label:'Feedback boundary', body:'The submission is assessed for fit, evidence, feasibility, originality, and voice. A selection engine applies the assumed rules and competing offers.', note:'The optimizer receives pass or fail. The researcher can inspect the underlying assessment.'},
];
export default function Showcase(){
  const hosted=import.meta.env.VITE_SHOWCASE_ONLY==='1';
  const repository='https://github.com/puedesleerlo/submission_standout';
  const [audience,setAudience]=useState<'recruiter'|'technical'>('recruiter');
  const [step,setStep]=useState(0),[observer,setObserver]=useState(false);
  const current=walkthrough[step];
  return <div className="showcase">
    <header className="showcase-nav"><a className="showcase-brand" href={hosted?'./':'/showcase'}><GitBranch size={22}/>Submission Standout</a><div><a href={repository} target="_blank" rel="noreferrer">Source code<ExternalLink size={14}/></a><a className="button primary" href={hosted?repository+'#run-locally':'/'}>{hosted?'Run locally':'Open workspace'}</a></div></header>
    <main><div className="audience-switch" role="group" aria-label="Choose your perspective"><button aria-pressed={audience==='recruiter'} onClick={()=>setAudience('recruiter')}>For recruiters</button><button aria-pressed={audience==='technical'} onClick={()=>setAudience('technical')}>For technical reviewers</button></div>
      <section className="showcase-intro"><h1>{audience==='recruiter'?'A better application starts with a testable strategy.':'Can an agent improve with only pass or fail?'}</h1><p>{audience==='recruiter'?'A working product for turning evidence into tailored submissions, comparing approaches, and preserving the reasoning behind every revision.':'A local research workbench for prompt-policy search under hidden selection rules. Separate what the learner observes from what the researcher measures.'}</p></section>
      {audience==='recruiter'?<>
        <section className="tour-workspace"><div className="tour-steps" role="group" aria-label="Product walkthrough">{walkthrough.map((s,i)=><button key={s.label} aria-pressed={step===i} onClick={()=>setStep(i)}><span>{i+1}</span>{s.label}{i===step&&<ArrowRight size={17}/>}</button>)}</div><div className="tour-document" aria-live="polite"><div className="document-top"><FileText size={19}/><span>Fictional fellowship walkthrough</span></div><h2>{current.title}</h2><p className="document-prose">{current.body}</p>{step===3&&<div className="tour-feedback"><div role="group" aria-label="Feedback visibility"><button aria-pressed={!observer} onClick={()=>setObserver(false)}>Learner</button><button aria-pressed={observer} onClick={()=>setObserver(true)}>Researcher</button></div>{observer?<div><strong>Rubric + rules + rivals</strong><p>Inspect criterion ratings, gates, rank, and the assumed selection scenario.</p></div>:<div><LockKeyhole size={18}/><strong>PASS / FAIL</strong><p>No score, critique, or rival profile crosses this boundary.</p></div>}</div>}<p className="tour-note">{current.note}</p><div className="tour-footer"><span>{step+1} of {walkthrough.length}</span><button className="button secondary" onClick={()=>setStep((step+1)%walkthrough.length)}>{step===3?'Restart walkthrough':'Next step'}<ArrowRight size={15}/></button></div></div></section>
        <section className="showcase-evidence"><div><h2>What this project demonstrates</h2><p>A complete workflow, from grounded inputs to editable artifacts and inspectable experiments.</p></div><ul><li><Check size={18}/><span>Product judgment: evidence and useful drafts come before model mechanics.</span></li><li><Check size={18}/><span>Engineering: a React interface, FastAPI jobs, immutable SQLite records, and scoped model calls.</span></li><li><Check size={18}/><span>Research judgment: test whether adaptation transfers, rather than showcasing a lucky draft.</span></li></ul></section>
      </>:<>
        <section className="technical-map" aria-label="Implemented architecture"><div className="map-source"><strong>Posting + public context</strong><span>Shared by both sides</span></div><div className="map-lanes"><div><h2>Submission side</h2><div className="map-node"><GitBranch size={18}/><span>Strategist<small>Versioned prompt policies</small></span></div><span className="map-arrow">↓</span><div className="map-node"><FileText size={18}/><span>Writer<small>Applicant evidence + policy</small></span></div></div><div><h2>Selection side</h2><div className="map-node"><ShieldCheck size={18}/><span>Selector designer<small>Assumed rubric, rules, rivals</small></span></div><span className="map-arrow">↓</span><div className="map-node"><Code2 size={18}/><span>Judge + allocation engine<small>LLM ratings; decisions in code</small></span></div></div></div><div className="map-boundary"><LockKeyhole size={18}/><strong>Pass/fail returns to the strategist</strong><span>Detailed diagnostics stay with the observer</span></div><div className="map-storage">SQLite audit trail · scoped API access · one trusted local backend</div></section>
        <section className="technical-protocol"><h2>Learning is a claim to test.</h2><div className="protocol-line"><div><strong>Train</strong><span>Search, branch, refine</span></div><ArrowRight size={20}/><div><strong>Validate & freeze</strong><span>Select saved policies</span></div><ArrowRight size={20}/><div><strong>Test</strong><span>Fresh opportunities and drafts</span></div></div><p>Five conditions: fixed drafting, random exploration, binary adaptation, privileged full feedback, and shuffled feedback. Matched competitor pools, fresh generations, opportunity-level estimates, and blinded human review.</p><a className="button secondary" href={hosted?repository+'/blob/main/docs/research-protocol.md':'/?view=research'}>{hosted?'Read the research protocol':'Inspect the research workbench'}<ArrowRight size={15}/></a></section>
        <section className="technical-limits"><h2>What the evidence does—and does not—show</h2><dl><div><dt>Optimization</dt><dd>Prompt-policy search. Model weights are not trained.</dd></div><div><dt>Selection theory</dt><dd>Inspired by scoring auctions. Hidden weights and synthetic rivals are assumptions, not recovered institutional preferences or equilibrium bidders.</dd></div><div><dt>Feedback controls</dt><dd>Training records are allowlisted. Test policies are frozen. Research traces never enter the everyday studio’s learner history.</dd></div><div><dt>Independent assessment</dt><dd>A capability-scoped human-review queue conceals methods and model scores. Review quality and sample size still matter.</dd></div><div><dt>Current limits</dt><dd>No evidence yet of higher real acceptance rates. No automatic external submissions, production sandbox, or calibrated population model.</dd></div></dl></section>
      </>}
      <footer className="showcase-footer"><div><strong>Built to be inspected.</strong><p>Explore the implementation, protocol, tests, and tradeoffs.</p></div><a className="button primary" href="https://github.com/puedesleerlo/submission_standout" target="_blank" rel="noreferrer">View on GitHub<ExternalLink size={15}/></a></footer>
    </main>
  </div>;
}
