export type Page = 'studio' | 'brief' | 'evidence' | 'strategies' | 'experiments' | 'research';
export interface Project { id: string; created_at: string; name: string; institution: string; posting: string; deadline: string; domain: string; focus: string[]; reservation_conditions: string; synthetic: boolean }
export interface Evidence { id: string; title: string; body: string; kind: string; source: string; status: string; synthetic: boolean; created_at: string }
export interface PolicyConfig { framing: 'evidence' | 'delivery' | 'hypothesis' | 'mission'; evidence_limit: number; plan_depth: number; compare_alternative: boolean }
export interface Policy { id: string; name: string; hypothesis: string; parents: string[]; version: number; operation: string; config: PolicyConfig; content_hash: string; created_at: string; author?: string; instructions?: string; tradeoff?: string; reflection?: string; learning_observation?: {policy_id:string;package_id:string;passed:boolean}[] }
export interface Package { id: string; policy_id: string; body: string; evidence_snapshot: Evidence[]; context_hash: string; content_hash: string; created_at: string; parent_id: string | null; generator: string; human_edited: boolean; title?:string; artifact_type?:string; missing_information?:string[]; voice_notes?:string; claims?:{claim:string;evidence_ids:string[]}[] }
export interface Scenario { id: string; name: string; probability: number; weights: Record<string, number> }
export interface Rating { dimension: string; score: number; explanation: string }
export interface World { index: number; scenario: Scenario; rivals: { name: string; score: number; features: Record<string, number> }[]; places: number; minimum_score: number; arrival_date: string; deadline: string; hash: string; rule: string }
export interface Trial { id: string; run_id: string; policy_id: string; package_id: string; observation: { passed: boolean }; package_hash: string; context_hash: string; paired_block_id: string; created_at: string; evaluation: { effective_places?:number; score: number; rank: number; passed: boolean; gates: { name: string; passed: boolean }[]; ratings: Rating[]; values: Record<string, number>; reason: string; world: World; evaluator: string; rubric_version: string; word_count: number; style_flags: string[] } }
export interface Run { id: string; created_at: string; policy_ids: string[]; package_ids: string[]; trial_ids: string[]; world_count: number; seed: number; delay_days: number; context_hash: string; protocol: string; origin: string; status: string; scenarios?:Scenario[]; selection_model_id?:string; cost: { elapsed_ms: number; external_cost_usd: number|null; model_calls: number; model_tokens?:number; reference_evaluations: number } }
export interface RunDetail extends Run { trials: Trial[]; summaries: { policy_id: string; passed: number; total: number; by_scenario: { scenario_id: string; name: string; passed: number; total: number }[] }[] }
export interface Workspace { project: Project; evidence: Evidence[]; policies: Policy[]; packages: Package[]; runs: Run[]; scenarios: Scenario[]; context_hash: string; events: { id: string; action: string; created_at: string; actor: string; details: Record<string, unknown> }[] }

export interface Provider { configured:boolean; model:string; provider:string; mode:string; max_calls_per_day:number }
export interface AgentJob { id:string; status:'queued'|'running'|'completed'|'failed'; mode:'develop'|'iterate'|'evaluate'; artifact_type:string; brief:string; stage:string; error?:string; run_id?:string; created_at:string; selection_model_id?:string; package_ids?:string[]; max_model_calls:number; steps:{id:string;stage:string;status:string;created_at:string}[] }
export interface SelectionModel { id:string; institutional_interests:string; source_basis:string[]; uncertainties:string[]; artifact_type:string; context_hash:string; rubric:{dimension:string;name:string;question:string;strong:string;weak:string}[]; scenarios:(Scenario & {rationale:string;rule:string})[] }
export interface Assessment { id:string; package_id:string; selection_model_id:string; ratings:Rating[]; strengths:string[]; weaknesses:string[]; style_flags:string[]; unsupported_claims:string[]; integrity_passed:boolean; integrity_reason:string; format_passed:boolean; format_reason:string }
export interface StudioData { jobs:AgentJob[]; selection_models:SelectionModel[]; assessments:Assessment[]; provider:Provider; packages:Package[]; policies:Policy[]; runs:Run[] }
